add review
sassansh/Places pull request #25
Opened 2021-06-19 20:34 UTC by johnnybcs

2021-06-20 02:40 UTC, sassansh requested changes

2021-06-20 02:40 UTC, sassansh commented on client/src/components/AddReview/AddReview.js
> +    alert(JSON.stringify(reviews));
Great implementation! 👏🏻But let's remove this debugging line. ⚠️

2021-06-20 02:42 UTC, sassansh commented
![image](https://user-images.githubusercontent.com/40008576/122660449-83867b80-d136-11eb-8e5d-4a8d11d75231.png)

Something more that can be done on this page is to render the place name, category and image based on the `CurrentPlaceID`

2021-06-20 18:43 UTC, johnnybcs commented
@sassansh Thanks for the suggestions. I've made changes so that the place rendered is based on place id. I also added a thank you page that appears after the review is submitted.

2021-06-21 01:33 UTC, sassansh approved these changes
![chrome-capture](https://user-images.githubusercontent.com/40008576/122695673-fdca0500-d1f5-11eb-9761-f43c1bd30a76.gif)

Tested! Working Beautiful. Go ahead and merge. ✅

2021-06-21 05:13 UTC, johnnybcs commented
@sassansh Thanks for the suggestions and code review!

2021-06-21 05:13 UTC, merged