Manage Group
sassansh/Places pull request #83
Opened 2021-07-21 21:21 UTC by amirjfr

2021-07-21 23:50 UTC, johnnybcs approved these changes
:D

2021-07-22 00:15 UTC, sassansh requested changes
![image](https://user-images.githubusercontent.com/40008576/126575098-dd03640d-34a2-46ad-b834-3b92dcc7742f.png)
Slightly misaligned with the text.
![image](https://user-images.githubusercontent.com/40008576/126575135-6e34f0ff-e92a-42f5-81b7-b888676bb6a0.png)
button drops below text when shrinking, is that expected?
![image](https://user-images.githubusercontent.com/40008576/126575153-c88b7717-bc6c-4d2c-9d9f-e738bdf7e476.png)
at mobile level, a bit cramped, can this be improved?

2021-07-22 00:15 UTC, sassansh commented on client/src/components/GroupView/GroupView.js
> +            {" "}
Does this need to be here?

2021-07-22 20:18 UTC, sassansh approved these changes

2021-07-22 20:18 UTC, merged